### ISSUE TITLE
--use_prepared_statements=0 in ci.yaml is broken

### ISSUE THREAD

**Issue by mjskier** [vertica/vertica-sql-go#115]
In init() in driver_test.go, the following 2 lines are commented out
```
testing.Init()
flag.Parse()
```
which means any arguments passed to `go test` in ci.yaml is not taken into consideration.
If you uncomment these 2 lines, you will find that tests with the `--use_prepared_statements=0` option fail with the following error in TestBasicArgsWithNil()
```
driver_test.go:353: Error: [42601] Syntax error at or near ","
```

**Comment by sitingren** [comment]
@mjskier Thanks for your report! I merged a quick fix for this issue.
