### ISSUE TITLE
The question mark in the string is interpreted as a placeholder

### ISSUE THREAD

**Issue by freecod** [vertica/vertica-sql-go#137]
ver. 1.2.1

Queries like 

`
create local temp table all_campaign_params on commit preserve rows direct as (select distinct case when pt.price == 0 then 'pr' else '' end, case when types like 'one%' then 'show?id=' else 'items' end as deeplink from spareparts_parameters sp);
`

when executed via ExecContext, they return the error "expected 1 arguments, got 0"

Apparently, the question mark in the line is perceived as a placeholder.

**Comment by sitingren** [comment]
Hi @freecod, Can you try this new release v1.2.2?

**Comment by freecod** [comment]
There is no problem on ver. 1.2.2, thank you!

**Comment by sitingren** [comment]
Great!
