### ISSUE TITLE
Set client_os_user_name and client_os on connection

### ISSUE THREAD

**Issue by scherepanov** [vertica/vertica-sql-go#147]
As of now, vertica-sql-go is the only one Vertica client that does not set fields client_os_user_name and client_os on connection.
All other Vertica clients are doing that.
Prime use of those fields are for audit.
Please set those fields on connection, should not be very hard.

**Comment by scherepanov** [comment]
I would "strongly" suggest to follow what Vertica ODBC and JDBC drivers are reporting in columns client_os. They both report same.
Users would be seeing same info for different drivers, and that is well within users expectations.
Looking at my audit records, here are samples of OS names:
Linux: Linux 4.16.13-300.fc28.x86_64 x86_64
Windows: Windows Server 2012 6.2.9200 x64
I do not have samples from OsX (Macbook).

**Comment by sitingren** [comment]
@scherepanov Even though ODBC and JDBC drivers are reporting the same client_os, other drivers are not, the OS info depends on the implementation of each programming language. For example, python driver returns 'Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.5.1804-Core', which gives much more detailed information. 

For vertica-sql-go I merged a solution to use a third-party package to construct client_os (e.g. 'CentOS Linux 3.10.0-957.5.1.el7.x86_64 x86_64'), the format would be similar to other drivers but cannot be the same. Feel free to make an enhancement if you can find a way to report the same client_os as ODBC and JDBC.

**Comment by scherepanov** [comment]
Thanks, that is a best efforts and good enough!

**Comment by scherepanov** [comment]
Implemented
