### ISSUE TITLE
No columns returned when query returns no rows

### ISSUE THREAD

**Issue by grzm** [vertica/vertica-sql-go#20]
When using prepared statements, if the query returns no rows, no columns are available.

Here's a repo-test: (https://github.com/grzm/vertica-sql-go/commit/dec2b63a05e4e841d2837ca1481633e93abf6262)

```go
func TestColumnsWithNoRows(t *testing.T) {
	connDB := openConnection(t)
	defer closeConnection(t, connDB)

	stmt, err := connDB.PrepareContext(ctx, "SELECT true AS res WHERE false")
	assertNoErr(t, err)
	rows, err := stmt.QueryContext(ctx)
	assertNoErr(t, err)

	columns, err := rows.Columns()
	assertNoErr(t, err)
	assertEqual(t, len(columns), 1) // this fails

	assertNoNext(t, rows)
}
```
`rows.Columns()` returns 0 columns, while there should be 1.

Comparing with vsql:

```
=> SELECT true AS res WHERE false;
 res 
-----
(0 rows)
```

**Comment by huebnerr** [comment]
Now that's a weird one. Let me try to repro and let you know @grzm.

**Comment by huebnerr** [comment]
@grzm, please refer to this PR. I've incorporated your test and have fixed the issue.
https://github.com/vertica/vertica-sql-go/pull/21

**Comment by grzm** [comment]
@huebnerr Thanks! It looks like that fixes the issue I was seeing.

A heads-up, it looks like there's also an issue with column names not being populated. I'm working on a repro test and will open a new issue when I've got it.

Off-hand, has there been any consideration in using https://github.com/lib/pq as a base? The PostgreSQL and Vertica wire protocols are really similar: I've sometimes used the PostgreSQL `psql` client to connect to Vertica servers. They've probably got a solid base from which to work from.

**Comment by huebnerr** [comment]
There's a long explanation there.  I looked at many bits of source code, including the one you suggest, vertica-python, the PG protocol spec, @tomwall's patience and direct reading of the protocol streams.

As I understand it, around ten or eleven years ago, the protocol forked. In some areas (e.g., simple queries) the PG protocol works just fine. In many others (e.g., portal/cursor semantics, extended attributes, etc.), not to mention metadata-level semantics, newer types, they're completely different.

The worst were finding ways there were subtly different.

Short answer: yep, looked and it helped kick off the journey. :)

**Comment by grzm** [comment]
Makes sense. Thanks!

**Comment by huebnerr** [comment]
PR merged. Closing issue.

**Comment by grzm** [comment]
Thanks!
