### ISSUE TITLE
Issues with test running under 1.13 using command line flags

### ISSUE THREAD

**Issue by huebnerr** [vertica/vertica-sql-go#33]
Due to breaking changes in Go 1.13, command line test flags are not being parsed correctly.

**Comment by deusnefum** [comment]
I just noticed this myself. Adding flag.Parse() to the init func in driver_test.go fixed it.

**Comment by huebnerr** [comment]
It works with 1.13 and breaks previous versions. This is due to a known breaking change in the Go testing framework.

On Sep 27, 2019 5:03 PM, Matthew Hiles <notifications@github.com> wrote:

I just noticed this myself. Adding flag.Parse() to the init func in driver_test.go fixed it.
