### ISSUE TITLE
Driver crashes when VERTICA_SQL_GO_LOG_FILE points to invalid or unwriteable location

### ISSUE THREAD

**Issue by langlbx** [vertica/vertica-sql-go#39]
When the file is writeable, you would normally see this:

Oct 14 17:02:09.311636 DEBUG connection: -> Bind: Portal='', Statement='S1815710725291106410694', ArgC=0
Oct 14 17:02:09.311812 DEBUG connection: -> Execute: Portal='', RowLimit=0
Oct 14 17:02:09.311922 DEBUG connection: <- Cmd Description: tag=SELECT, hasRewrite=false, rewrite=''
Oct 14 17:02:09.391896 DEBUG connection: <- Error: [42501] Permission denied for relation cpu_usage
Oct 14 17:02:09.392008 DEBUG connection: -> Close: TargetType=S, TargetName='S1815710725291106410694'

However, the entire process seems to crash when the file is not writeable.

**Comment by huebnerr** [comment]
After trying several variants, I am unable to reproduce this bug.
