### ISSUE TITLE
Hang when creating an already existing table inside transaction.

### ISSUE THREAD

**Issue by fbernier** [vertica/vertica-sql-go#48]
I have an endpoint that is creating a temporary table inside a transaction. That create table statement didn't have `IF NOT EXIST` and since go sql re-uses connections, I would often fall on a connection that already had this table.

When that was the case, it would just hang on the create table. I ended up figuring out what the problem was when I saw this when stracing the process.

```
[pid 129981] read(6, "SROLLBACK\0C42710\0V4213\0MObject \"temp_ids\" already exists\0F/data/qb_workspaces/jenkins2/ReleaseBuilds/Grader/REL-9_2_0-x_grader/build/vertica/Commands/DDL.cpp\0L2
2038\0RoutputAlreadyExistsEreport\0\0", 196) = 196
```

I am probably going to make a PR with a failing test when I have time.

**Comment by huebnerr** [comment]
Interesting! Will check.

Thanks
