### ISSUE TITLE
does not handle sql comments with question mark

### ISSUE THREAD

**Issue by watercraft** [vertica/vertica-sql-go#54]
I had a large query that had a question mark in the SQL comments (after --).  This resulted in an error "sql:  expected 1 arguments, got 0".  It took me a while to track this down, but the question mark is used by this driver's NumInput() function to indicate the presence of an argument.  As alexbrainman/odbc doesn't have this issue I suspect there is another way to evaluate this property. For now I have removed the question mark and the query seems to be working correctly.

**Comment by huebnerr** [comment]
Thanks, @watercraft. I've actually seen this issue in the past and thought I had opened up an issue on it. This was seen with and without question marks under various circumstances. The simple solution would be to pre-parse away all comments before passing them to Vertica.

I'll work on adding that.

**Comment by sitingren** [comment]
Parsing away all comments is not enough. Question marks can also appear in values, `select * from x where c='whatever?'`. A more safe way is to tokenize the sql.

**Comment by huebnerr** [comment]
But something lopped off after -- will not affect this.  In other words,

select * from x where c='whatever?' -- what happened here?

will just be transformed into:

select * from x where c="whatever?"

**Comment by huebnerr** [comment]
@watercraft, please confirm this is indicative of your issue.

**Comment by sitingren** [comment]
@huebnerr What I mean is [`interpolate()`](https://github.com/vertica/vertica-sql-go/blob/90a9cc4d91a5c60e50e91921220775657a018319/stmt.go#L274) is very fragile as it just replaces question marks without any restriction. If the sql is `select * from x where c1="whatever?" and c2=?`, and you pass one parameter. Will you replace the question mark in c1? or c2?

@watercraft What's your `use_prepared_statements` setting in the connection string?

**Comment by huebnerr** [comment]
@sitingren You're right. interpolate() is pretty naive in that matter.

**Comment by mlh758** [comment]
I have a change coming together that should fix this issue as a side effect of emulating named parameters.
