### ISSUE TITLE
bind of boolean values to front end message is broken

### ISSUE THREAD

**Issue by watercraft** [vertica/vertica-sql-go#56]
Here is my proposed fix (from watercraft/vertica-sql-go):
```
commit 5dce60aad881d8efe99112a6676c58f80c964c96 (HEAD -> master, origin/master, origin/HEAD)
Author: Alan Jones <alan@zebrium.com>
Date:   Mon Jan 20 14:32:56 2020 -0800

    fix binding of binary values to frontend message

diff --git a/msgs/febindmsg.go b/msgs/febindmsg.go
index 0326ce0..568121f 100644
--- a/msgs/febindmsg.go
+++ b/msgs/febindmsg.go
@@ -75,9 +75,9 @@ func (m *FEBindMsg) Flatten() ([]byte, byte) {
                        strVal = v
                case bool:
                        if v {
-                               strVal = "t"
+                               strVal = "1"
                        } else {
-                               strVal = "f"
+                               strVal = "0"
                        }
                case time.Time:
                        strVal = v.Format("2006-01-02T15:04:05.999999Z07:00")
```

**Comment by huebnerr** [comment]
Strange that that hasn't been sufficiently tested. @watercraft, thanks for the fix. @sitingren, can you verify this fix?

**Comment by fbernier** [comment]
Looks like the change matches the python driver: https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/messages/frontend_messages/bind.py#L95-L97

**Comment by sitingren** [comment]
Yes, Boolean values send to the server should be expressed as 0/1.

**Comment by huebnerr** [comment]
It looks good to me. @fbernier , @watercraft : would either of you like to do a PR (and update the tests so that this will get caught.)?  If not, I can add it to my list.

**Comment by huebnerr** [comment]
p.s., need to add a "Special Thanks" section to the README.md. You two and quite a few others have made some great contributions to the driver.

**Comment by huebnerr** [comment]
Fixed in https://github.com/vertica/vertica-sql-go/pull/58
