### ISSUE TITLE
Named params with in clause

### ISSUE THREAD

**Issue by mlh758** [vertica/vertica-sql-go#70]
The named parameter implementation doesn't work right with an in clause:

`select * from whatever where a in (@first, @second)`

for example. I'll submit a PR to fix this along with a test case. 

When it hits an `@` it consumes to the next white space, but with an in clause there could be a comma or parenthesis indicating the end of the identifier instead.

**Comment by huebnerr** [comment]
Lex/Yacc are tempermental and dangerous allies!

**Comment by mlh758** [comment]
You could say I was lexadaisical about where the parameters could appear.

**Comment by huebnerr** [comment]
Will review and merge.
