### ISSUE TITLE
`local error: tls: no renegotiation` when using TLS

### ISSUE THREAD

**Issue by fbernier** [vertica/vertica-sql-go#75]
Hey,

We noticed that after ~500mb transferred during a response, we'ew getting a `local error: tls: no renegotiation` error. I'm wondering what's the best way to deal with this. The options I see are:

1- ```config := &tls.Config{
    Renegotiation: tls.RenegotiateFreelyAsClient,
}``` in `vertica-sql-go`
2- Disable tls renegociations in Vertica but I'm not entirely sure this is possible.

I saw https://www.vertica.com/docs/ReleaseNotes/9.1.x/Vertica_9.1.x_Release_Notes.htm
(ctrl+f tls_renegotiation_limit) but this seems to be limited to the jdbc driver and I'm not sure how to replicate this.

Any advice?

**Comment by huebnerr** [comment]
Thanks for the report. I'm going to ask @tomwall (who wrote the jdbc driver) for details. It certainly sounds like renegotiation is where we're hitting the problem. I'll let you know what I find out!

**Comment by tomwall** [comment]
tls_renegotiation_limit is the parameter you need. 

It was invented to avoid interop bugs between openssl (vertica server) and not-openssl TLS implementations (various vertica clients) during renegotiation. Newer vertica versions default it to 0 but in 9.1.x you probably need to set it to 0 manually to disable renegotiation. You can do so with something like: `alter database default set tls_renegotiation_limit=0`

It was first found in the context of some JDBC applications (JVM TLS implementation; hence the release note mention), but the parameter is a server-side setting. You're probably experiencing the same interop problem in go's TLS implementation.

**Comment by fbernier** [comment]
Thanks, I'm gonna try this out. Perhaps I could suggest to add this to the documentation as I've been unable to find a reference to this parameter other than the excerpt in the release notes.

**Comment by fbernier** [comment]
@tomwall  tried it on a server running Vertica 9.2 (on which we get the renegotiation error) and got the following: `ROLLBACK 3638:  Invalid configuration parameter tls_renegotiation_limit; aborting configuration change`

**Comment by tomwall** [comment]
It sounds like you'll need to upgrade to a version that has the parameter. If you are using 9.2.x, the fix was introduced in 9.2.1 (https://www.vertica.com/docs/ReleaseNotes/9.2.x/Vertica_9.2.x_Release_Notes.htm). If you are using 9.1.x, the fix was added in 9.1.1-7. 

I will relay the feedback to the doc team. In the meantime, the full listing of parameters and a description of each can be seen via the v_monitor.configuration_parameters table.

**Comment by huebnerr** [comment]
Thanks, @tomwall !
