### ISSUE TITLE
Arg types of sql.Null* with Valid=false get converted to "??HELP??" string in the driver

### ISSUE THREAD

**Issue by Maunte** [vertica/vertica-sql-go#84]
When executing a statement with sql.Null* args, where the arg's Valid=false, the execution fails, or has an unexpected outcome.  If the arg is a NullString, it is persisted as "??HELP??".  If it is a non-string type, the error "Invalid input syntax for <type>: "??HELP??" is thrown.  To reproduce:

    db, _ := sql.Open("vertica", <connectionStrint>)
    var nullString = sql.NullString{"", false}
    var nullInt64 = sql.NullInt64{0, false}
    
    // "CREATE TABLE test_table (null_string VARCHAR, null_int INTEGER) ORDER BY null_String"
    var insert = "INSERT INTO test_table (null_string, null_int) VALUES (?, ?)"

    db.Exec(insert, nullString, 0)  // Passes, but inserts '??HELP??' to null_string column
    db.Exec(insert, "", nullInt64)  // throws error "Invalid input syntax for integer: ??HELP??"
    db.Exec(insert, "", nil)  // throws error "Invalid input syntax for integer: ??HELP??"

Adding a nil case to the febingmsg.go type switch seems to solve the problem.  It seems that, because the driver does not implement the NamedValueChecker interface, and the sql.Null* types are not considered valid driver.Value types, the values get converted to nil in the golang sql module before they are passed to the driver, so the case statement in febindmsg.go for Null* types never is reached.

Tested with golang v1.11.2, 1.12, and 1.13.

**Comment by mlh758** [comment]
I hit a similar problem, should have a PR up in a few days.
