### ISSUE TITLE
Does it support COPY FROM / COPY TO ? 

### ISSUE THREAD

**Issue by ankit1986** [vertica/vertica-sql-go#9]
Does it support COPY FROM / COPY TO ? 

I couldnt find any reference for it in the docs / code.

**Comment by huebnerr** [comment]
Not yet, although that functionality is certainly possible to add. Discussions have begun in-house on the next round of features and we'll make sure to take note of the request. That being said, we would also be grateful for any contributions to the code base.

**Comment by baron42bba** [comment]
As soon as CopyStream is available I am going to switch from Perl/ODBC.

**Comment by huebnerr** [comment]
That sounds great. I've already added it to the backlog.

**Comment by huebnerr** [comment]
@baron42bba @ankit1986 Can either of you spell out the exact commands you need to have executed? Many COPY variants will work today, but a few specific cases (such as COPY LOCAL) are being worked on.

**Comment by ankit1986** [comment]
Yes COPY FROM LOCAL or GLOBAL would be awesome. I intended to run these types of queries:
```CREATE LOCAL TEMP TABLE someTable (id int, email string);
COPY someTable(id AS -2, email) FROM LOCAL '/tmp/email_backfill';```

At present I'm using vsql (command line) and running these commands from go exec.

**Comment by baron42bba** [comment]
Currently I am using something like

COPY schema.foo
  FROM LOCAL 'filename'
  WITH DELIMITER e'\036'
  ENCLOSED BY '' RECORD TERMINATOR e'\34' NULL e'\37'
  EXCEPTIONS '/mnt/temp/storage/dbadmin/foo-42.exception'
  REJECTED DATA '/mnt/temp/storage/dbadmin/foo-42.rejected';

but I would like to be able to use this from go:

COPY schema.foo
  FROM STDIN
  WITH DELIMITER e'\036'
  ENCLOSED BY '' RECORD TERMINATOR e'\34' NULL e'\37'
  EXCEPTIONS '/mnt/temp/storage/dbadmin/foo-42.exception'
  REJECTED DATA '/mnt/temp/storage/dbadmin/foo-42.rejected';

as referred in the JDBC Manual:

https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/ConnectingToVertica/ClientJDBC/UsingVerticaCopyStream.htm

**Comment by huebnerr** [comment]
That sounds great. It seems COPY LOCAL is in demand for sure. I did some poking around last night and see how to add it. I'll get it scheduled into the near term development work. Keep watching this thread for update. Thanks again!

**Comment by huebnerr** [comment]
@ankit1986 @baron42bba @sitingren @tomwall

I've prototyped some functionality in branch 'rhuebner-stdin-experimental'. This functionality will allow you to use 'COPY STDIN' (not 'COPY LOCAL STDIN') to copy either from stdin (if you're writing a command-line tool for example) OR to specify the stream from which to read. In both cases, copies will continue until EOF is reached.

To use the former form, just call the regular "copy stdin" style.  Example:
_, err = connDB.ExecContext(ctx, "COPY stdin_data FROM STDIN DELIMITER ','")

To use an alternate stream, programmatically, do something similar to:

fp, err := os.OpenFile("./resources/csv/sample_data.csv", os.O_RDONLY, 0600)
...
_, err = connDB.ExecContext(context.WithValue(ctx, "stdin.stream", fp), "COPY stdin_data FROM STDIN DELIMITER ','")

Please try this out and let me know if this helps meet your requirements. Once approved, we can continue looking at the COPY LOCAL filename scenarios.

**Comment by huebnerr** [comment]
Please note that the argument passed to NewVerticaContext() is the parent context you're using. The VerticaContext will inherit all of its properties and behaviors. At the moment the only differences are the new methods we've added.

**Comment by baron42bba** [comment]
Thanks a lot. I was busy with Vertica recovery tests and upgrades.
I am going to test early next week.

**Comment by huebnerr** [comment]
Since I'll need this code to implement some further features. I'll submit to a PR. Please test and close against main branch when you get time. Thanks.

**Comment by baron42bba** [comment]
Sorry for the delay. I had to first learn a bit of go :-)
This one is working:
`	vCtx := vertigo.NewVerticaContext(ctx)
	vCtx.SetCopyInputStream(fp)

	_, err = connDB.ExecContext(vCtx, "COPY public.stdin_data FROM STDIN DELIMITER e'\036' ENCLOSED BY '\"' RECORD TERMINATOR e'\034' NULL e'\037'")
`

**Comment by huebnerr** [comment]
Thank you for validating, @baron42bba. We'll mark this one closed and continue on to the LOCAL variants. If there are any other priority use cases, please let us know.
