### ISSUE TITLE
adding TLS mutual authentication to vertica-sql-go

### ISSUE THREAD

**Issue by ehrt74** [vertica/vertica-sql-go#90]
Hello! I'd like to add tls to vertica-sql-go. Probably best to implement it like in the mysql-library (see RegisterTLSConfig here: https://github.com/go-sql-driver/mysql/blob/3b935426341bc5d229eafd936e4f4240da027ccd/utils.go)

**Comment by vodrazka** [comment]
oh yes! +1

**Comment by ldrozdowski** [comment]
+1
